/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiWysiwyg from "strapi-html-editor/strapi-admin";
import menus from "strapi-plugin-menus/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import editorjs from "strapi-plugin-react-editorjs/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.js";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    calendar: calendar,
    "color-picker": colorPicker,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-wysiwyg": strapiWysiwyg,
    menus: menus,
    navigation: navigation,
    editorjs: editorjs,
  },
});
